version: '3.1'

services:
  mongo:
    image: mongo:6.0.5-jammy
    restart: always
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: 123
    ports:
      - "27017:27017"
    volumes:
      - local-mongo:/data/db
    command: [ --auth ]

volumes:
  local-mongo:
    driver: local